services:
  gamevault:
    image: ${DOCKER_REGISTRY-}gamevault
    container_name: game_vault_api
    build:
      context: .
      dockerfile: GameVault/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - "db"
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Ravindra@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: